In [2]:
#1
import tensorflow as tf

scalar_tensor =tf.constant(10)
print("Tensor value:",scalar_tensor)
print("Tensor data type:",scalar_tensor.dtype)

Tensor value: tf.Tensor(10, shape=(), dtype=int32)
Tensor data type: <dtype: 'int32'>


In [3]:
#2
vector=tf.constant([2,4,6,8])
print("Tensor value:",vector)
print("tensor shape:",vector.shape)
print("Numpy value:",vector.numpy())


Tensor value: tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tensor shape: (4,)
Numpy value: [2 4 6 8]


In [4]:
#3
matrix = tf.constant([[1, 2], [3, 4]])
print("Tensor value:",vector)
print("tensor shape:",vector.shape)
print("tensor shape:",vector.dtype)


Tensor value: tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tensor shape: (4,)
tensor shape: <dtype: 'int32'>


In [6]:
#4
v = tf.Variable(5.0)
print("Initial Value:",v.numpy())


Initial Value: 5.0


In [7]:
#5
v.assign(10.0)
print("updated value:",v.numpy())

updated value: 10.0


In [12]:
#6
matrix_var = tf.Variable([[1.0, 2.0],
                           [3.0, 4.0]])
matrix_var.assign_add([[1.0, 1.0], [1.0, 1.0]])
print("After assign_add():\n", matrix_var.numpy())

After assign_add():
 [[2. 3.]
 [4. 5.]]


In [13]:
#7

x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2 + 2*x + 1

print("x value:", x.numpy())
print("y value:", y.numpy())



x value: 3.0
y value: 16.0


In [14]:
#8
dy_dx = tape.gradient(y, x)
print("Gradient dy/dx:", dy_dx.numpy())



Gradient dy/dx: 8.0


In [15]:
#9
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[5, 6],
                 [7, 8]])

matmul_result = tf.matmul(a, b)
print("Matrix multiplication result:\n", matmul_result.numpy())


Matrix multiplication result:
 [[19 22]
 [43 50]]


In [16]:
#10
random_tensor = tf.random.uniform((3, 3))
print("Random tensor shape:", random_tensor.shape)
print("Random tensor dtype:", random_tensor.dtype)
print("Random tensor values:\n", random_tensor.numpy())

Random tensor shape: (3, 3)
Random tensor dtype: <dtype: 'float32'>
Random tensor values:
 [[0.3415904  0.7532959  0.2552781 ]
 [0.35528445 0.94739795 0.27455223]
 [0.79953027 0.5625644  0.813982  ]]
